
<style id="ko-portfolio-return">
.ko-portfolio-return{position:fixed;left:20px;bottom:20px;z-index:99999;display:inline-flex;align-items:center;gap:9px;padding:13px 18px;border:1px solid rgba(255,255,255,.22);border-radius:999px;background:rgba(8,8,8,.88);backdrop-filter:blur(14px);color:#fff;text-decoration:none;font:600 12px/1 Inter,Arial,sans-serif;box-shadow:0 10px 35px rgba(0,0,0,.3);transition:.25s}.ko-portfolio-return:hover{transform:translateY(-3px);border-color:#d7ff45;color:#d7ff45}.ko-portfolio-return .ko-arrow{font-size:17px}@media(max-width:600px){.ko-portfolio-return{left:12px;bottom:12px;padding:11px 14px;font-size:11px}}
</style>
<?php $pageTitle='Tee Time | K.O. Divinii'; $active='golf'; require 'includes/header.php'; ?>
<section class="page-hero"><div class="container reveal"><div class="section-kicker">K.O. Divinii • Tee time</div><h1>Find your <em>line.</em><br>Own the round.</h1><p>Submit a preferred tee slot and our desk can confirm it with you. The form is wired to the included MySQL database.</p></div></section>
<section class="section"><div class="container form-shell"><aside class="form-aside reveal"><div class="section-kicker">The first tee</div><h2>Make the morning count.</h2><p class="body-copy">The reference film is built around a close, tactile moment: club head, turf, ball. This page carries that same visual intimacy into the booking experience.</p><div class="check-list"><div><i class="fa-regular fa-clock"></i><span>Preferred tee time</span></div><div><i class="fa-solid fa-people-group"></i><span>Up to 4 players per request</span></div><div><i class="fa-solid fa-bell-concierge"></i><span>Concierge confirmation</span></div></div></aside>
<div class="card reveal"><form action="actions/booking.php" method="post"><div class="form-grid"><div class="field"><label>Player name</label><input name="name" required maxlength="120"></div><div class="field"><label>Email</label><input name="email" type="email" required maxlength="190"></div><div class="field"><label>Date</label><input name="tee_date" type="date" required min="<?= date('Y-m-d') ?>"></div><div class="field"><label>Preferred time</label><input name="tee_time" type="time" required></div><div class="field"><label>Players</label><select name="players"><option>1</option><option selected>2</option><option>3</option><option>4</option></select></div><div class="field"><label>Guest note</label><input name="notes" maxlength="255" placeholder="Optional"></div></div><button class="btn primary" style="margin-top:18px">Request this tee time <i class="fa-solid fa-arrow-right"></i></button><div class="form-note">A booking remains pending until the club confirms it.</div></form></div></div></section>
<?php require 'includes/footer.php'; ?>

<a class="ko-portfolio-return" href="/KO_DIVINII_CV/#works" aria-label="Return to K.O DIVINII portfolio"><span class="ko-arrow">←</span> Back to Portfolio</a>
