
<style id="ko-portfolio-return">
.ko-portfolio-return{position:fixed;left:20px;bottom:20px;z-index:99999;display:inline-flex;align-items:center;gap:9px;padding:13px 18px;border:1px solid rgba(255,255,255,.22);border-radius:999px;background:rgba(8,8,8,.88);backdrop-filter:blur(14px);color:#fff;text-decoration:none;font:600 12px/1 Inter,Arial,sans-serif;box-shadow:0 10px 35px rgba(0,0,0,.3);transition:.25s}.ko-portfolio-return:hover{transform:translateY(-3px);border-color:#d7ff45;color:#d7ff45}.ko-portfolio-return .ko-arrow{font-size:17px}@media(max-width:600px){.ko-portfolio-return{left:12px;bottom:12px;padding:11px 14px;font-size:11px}}
</style>
<?php $pageTitle='Contact | K.O. Divinii'; $active='contact'; require 'includes/header.php'; ?>
<section class="page-hero"><div class="container reveal"><div class="section-kicker">K.O. Divinii • Concierge</div><h1>Consider this your <em>invitation.</em></h1><p>For membership, guest visits, events or clubhouse enquiries, send the desk a note.</p></div></section>
<section class="section"><div class="container contact-grid"><div class="contact-cards reveal"><div class="contact-card"><i class="fa-solid fa-location-dot"></i><span>Clubhouse</span><b>Victoria Island, Lagos</b></div><div class="contact-card"><i class="fa-solid fa-phone"></i><span>Concierge line</span><b>+234 800 000 0000</b></div><div class="contact-card"><i class="fa-regular fa-envelope"></i><span>Email</span><b>concierge@kodivinii.com</b></div></div><div class="card reveal"><form action="actions/contact.php" method="post"><div class="form-grid"><div class="field"><label>Name</label><input name="name" required maxlength="120"></div><div class="field"><label>Email</label><input name="email" type="email" required maxlength="190"></div><div class="field full"><label>Subject</label><input name="subject" maxlength="180"></div><div class="field full"><label>Message</label><textarea name="message" required></textarea></div></div><button class="btn primary" style="margin-top:18px">Send to concierge <i class="fa-solid fa-paper-plane"></i></button></form></div></div></section>
<?php require 'includes/footer.php'; ?>

<a class="ko-portfolio-return" href="/KO_DIVINII_CV/#works" aria-label="Return to K.O DIVINII portfolio"><span class="ko-arrow">←</span> Back to Portfolio</a>
