
<style id="ko-portfolio-return">
.ko-portfolio-return{position:fixed;left:20px;bottom:20px;z-index:99999;display:inline-flex;align-items:center;gap:9px;padding:13px 18px;border:1px solid rgba(255,255,255,.22);border-radius:999px;background:rgba(8,8,8,.88);backdrop-filter:blur(14px);color:#fff;text-decoration:none;font:600 12px/1 Inter,Arial,sans-serif;box-shadow:0 10px 35px rgba(0,0,0,.3);transition:.25s}.ko-portfolio-return:hover{transform:translateY(-3px);border-color:#d7ff45;color:#d7ff45}.ko-portfolio-return .ko-arrow{font-size:17px}@media(max-width:600px){.ko-portfolio-return{left:12px;bottom:12px;padding:11px 14px;font-size:11px}}
</style>
<?php $pageTitle='Membership | K.O. Divinii'; $active='membership'; require 'includes/header.php'; ?>
<section class="page-hero"><div class="container reveal"><div class="section-kicker">K.O. Divinii • Membership</div><h1>Membership for people who want the club to feel <em>personal.</em></h1><p>Private access, tailored hospitality and a calendar of golf and gatherings built around the people you actually want to see.</p></div></section>
<section class="section"><div class="container form-shell"><aside class="form-aside reveal"><div class="section-kicker">Membership desk</div><h2>Make an introduction.</h2><p class="body-copy">Tell us how you play and what you enjoy. Our membership team will respond with the right pathway.</p><div class="check-list"><div><i class="fa-solid fa-check"></i><span>Private member tee access</span></div><div><i class="fa-solid fa-check"></i><span>Clubhouse dining & social calendar</span></div><div><i class="fa-solid fa-check"></i><span>Guest privileges subject to club policy</span></div><div><i class="fa-solid fa-check"></i><span>Priority concierge support</span></div></div></aside>
<div class="card reveal"><form action="actions/membership.php" method="post"><div class="form-grid"><div class="field"><label>Full name</label><input name="name" required maxlength="120" placeholder="Your full name"></div><div class="field"><label>Email</label><input type="email" name="email" required maxlength="190" placeholder="you@example.com"></div><div class="field"><label>Phone</label><input name="phone" maxlength="40" placeholder="+234 …"></div><div class="field"><label>Membership interest</label><select name="membership_type" required><option value="Full Member">Full Member</option><option value="Corporate">Corporate</option><option value="Young Professional">Young Professional</option><option value="Social">Social</option></select></div></div><button class="btn primary" style="margin-top:18px">Send membership enquiry <i class="fa-solid fa-arrow-right"></i></button><div class="form-note">This demo stores enquiries in MySQL. Connect it to your preferred mail service for production notifications.</div></form></div></div></section>
<?php require 'includes/footer.php'; ?>

<a class="ko-portfolio-return" href="/KO_DIVINII_CV/#works" aria-label="Return to K.O DIVINII portfolio"><span class="ko-arrow">←</span> Back to Portfolio</a>
